# Generated by Django 5.2.8 on 2025-11-19 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS idx_option_poll_id 
            ON polls_option(poll_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_option_poll_id;"
        ),
    ]
