# Generated by Django 5.2.8 on 2025-11-19 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_poll_idx_polls_expires_at_poll_idx_polls_is_public_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["expires_at"], name="idx_polls_expires_at"),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["is_public"], name="idx_polls_is_public"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["poll", "option"], name="idx_votes_poll_option"),
        ),
    ]
