# Generated by Django 5.2.8 on 2025-11-24 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_poll_idx_polls_expires_at_poll_idx_polls_is_public_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_user_poll_vote",
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user", "option"), name="unique_user_poll_vote"
            ),
        ),
    ]
